# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnNGDSkhu8fdF3HXX-u-aHhSNly-kD7s
"""

!pip install kaggle opencv-python-headless scikit-learn umap-learn matplotlib seaborn plotly streamlit mlflow -q
print("✓ All libraries installed")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import pickle
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.ensemble import IsolationForest
import umap

plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
print("✓ All imports done")

import os

# Setup kaggle credentials
os.makedirs('/root/.kaggle', exist_ok=True)
os.system('cp kaggle.json /root/.kaggle/')
os.system('chmod 600 /root/.kaggle/kaggle.json')

# Download dataset

os.system('kaggle datasets download -d paultimothymooney/chest-xray-pneumonia --unzip -p /content/chest_xray')
print("✓ Download complete!")

import glob
all_images = glob.glob('/content/chest_xray/**/*.jpeg', recursive=True)
print(f"Total images found: {len(all_images)}")

import glob
IMG_SIZE   = 128
MAX_IMAGES = 600

all_images = glob.glob('/content/chest_xray/**/*.jpeg', recursive=True)
all_images = all_images[:MAX_IMAGES]
print(f"Loading {len(all_images)} images...")

images      = []
image_paths = []
labels      = []

for path in all_images:
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img / 255.0
        images.append(img.flatten())
        image_paths.append(path)
        label = 'PNEUMONIA' if 'PNEUMONIA' in path else 'NORMAL'
        labels.append(label)

images = np.array(images)
print(f"✓ Loaded {len(images)} images")
print(f"Normal:    {labels.count('NORMAL')}")
print(f"Pneumonia: {labels.count('PNEUMONIA')}")

# Chart 1 — Sample images
fig, axes = plt.subplots(2, 5, figsize=(15, 6))
fig.suptitle('Sample Chest X-Ray Images', fontsize=14, fontweight='bold')

normal_paths    = [p for p,l in zip(image_paths,labels) if l=='NORMAL'][:5]
pneumonia_paths = [p for p,l in zip(image_paths,labels) if l=='PNEUMONIA'][:5]

for i, path in enumerate(normal_paths):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    img = cv2.resize(img, (128,128))
    axes[0,i].imshow(img, cmap='gray')
    axes[0,i].set_title('NORMAL', color='green', fontweight='bold')
    axes[0,i].axis('off')

for i, path in enumerate(pneumonia_paths):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    img = cv2.resize(img, (128,128))
    axes[1,i].imshow(img, cmap='gray')
    axes[1,i].set_title('PNEUMONIA', color='red', fontweight='bold')
    axes[1,i].axis('off')

plt.tight_layout()
plt.show()

# Chart 2 — Distribution
fig, ax = plt.subplots(figsize=(8,5))
label_counts = pd.Series(labels).value_counts()
ax.bar(label_counts.index, label_counts.values,
       color=['#378ADD','#D85A30'], width=0.4)
ax.set_title('Dataset Distribution', fontsize=14, fontweight='bold')
ax.set_ylabel('Count')
for i,(label,count) in enumerate(label_counts.items()):
    ax.text(i, count+2, str(count), ha='center', fontweight='bold')
plt.tight_layout()
plt.show()
print("INSIGHT: Normal lungs appear clear. Pneumonia shows white patches.")

print("Running PCA...")
scaler     = StandardScaler()
images_scaled = scaler.fit_transform(images)

pca        = PCA(n_components=50, random_state=42)
images_pca = pca.fit_transform(images_scaled)

print(f"✓ PCA done")
print(f"Original shape:   {images.shape}")
print(f"PCA shape:        {images_pca.shape}")
print(f"Variance explained: {pca.explained_variance_ratio_.sum()*100:.1f}%")

fig, ax = plt.subplots(figsize=(10,5))
ax.plot(np.cumsum(pca.explained_variance_ratio_)*100,
        color='#378ADD', linewidth=2)
ax.axhline(y=80, color='#D85A30', linestyle='--', label='80% threshold')
ax.set_title('PCA — Cumulative Explained Variance', fontsize=14, fontweight='bold')
ax.set_xlabel('Number of Components')
ax.set_ylabel('Cumulative Explained Variance (%)')
ax.legend()
plt.tight_layout()
plt.show()

import umap as umap_lib

reducer      = umap_lib.UMAP(n_components=2, random_state=42,
                               n_neighbors=15, min_dist=0.1)
images_umap  = reducer.fit_transform(images_pca)
print("✓ UMAP done")

fig, ax = plt.subplots(figsize=(10,8))
colors  = ['#378ADD' if l=='NORMAL' else '#D85A30' for l in labels]
ax.scatter(images_umap[:,0], images_umap[:,1],
           c=colors, alpha=0.6, s=20)
ax.set_title('UMAP Projection of X-ray Images', fontsize=14, fontweight='bold')
ax.set_xlabel('UMAP 1'); ax.set_ylabel('UMAP 2')
from matplotlib.patches import Patch
ax.legend(handles=[Patch(facecolor='#378ADD', label='NORMAL'),
                   Patch(facecolor='#D85A30', label='PNEUMONIA')])
plt.tight_layout()
plt.show()
print("INSIGHT: UMAP separates normal and pneumonia into distinct clusters.")

print("Running K-Means...")
inertias = []
K_range  = range(2, 10)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(images_pca)
    inertias.append(km.inertia_)

fig, ax = plt.subplots(figsize=(10,5))
ax.plot(K_range, inertias, 'bo-', linewidth=2, markersize=8)
ax.set_title('K-Means Elbow Method', fontsize=14, fontweight='bold')
ax.set_xlabel('Number of Clusters (K)')
ax.set_ylabel('Inertia')
plt.tight_layout()
plt.show()

best_k    = 3
kmeans    = KMeans(n_clusters=best_k, random_state=42, n_init=10)
km_labels = kmeans.fit_predict(images_pca)
sil_score = silhouette_score(images_pca, km_labels)

print(f"✓ K-Means done — K={best_k}")
print(f"Silhouette Score: {sil_score:.4f}")
print(f"Cluster sizes: {pd.Series(km_labels).value_counts().to_dict()}")

fig, ax = plt.subplots(figsize=(10,8))
colors_km = ['#378ADD','#D85A30','#1D9E75']
for cluster in range(best_k):
    mask = km_labels == cluster
    ax.scatter(images_umap[mask,0], images_umap[mask,1],
               c=colors_km[cluster], alpha=0.6, s=20,
               label=f'Cluster {cluster}')
ax.set_title('K-Means Clusters on UMAP', fontsize=14, fontweight='bold')
ax.set_xlabel('UMAP 1'); ax.set_ylabel('UMAP 2')
ax.legend()
plt.tight_layout()
plt.show()
print(f"INSIGHT: K-Means found {best_k} natural clusters in X-ray data.")

print("Running Isolation Forest anomaly detection...")
iso_forest     = IsolationForest(contamination=0.1,
                                  random_state=42, n_estimators=100)
anomaly_labels = iso_forest.fit_predict(images_pca)
anomaly_scores = iso_forest.decision_function(images_pca)

n_anomalies = (anomaly_labels == -1).sum()
print(f"✓ Done")
print(f"Total images:      {len(anomaly_labels)}")
print(f"Anomalies detected:{n_anomalies} ({n_anomalies/len(anomaly_labels)*100:.1f}%)")

fig, ax = plt.subplots(figsize=(10,8))
normal_mask  = anomaly_labels == 1
anomaly_mask = anomaly_labels == -1
ax.scatter(images_umap[normal_mask,0], images_umap[normal_mask,1],
           c='#378ADD', alpha=0.4, s=15, label='Normal')
ax.scatter(images_umap[anomaly_mask,0], images_umap[anomaly_mask,1],
           c='#D85A30', alpha=0.8, s=60, label='Anomaly/Misplaced', marker='*')
ax.set_title('Anomaly Detection — Misplaced X-rays', fontsize=14, fontweight='bold')
ax.set_xlabel('UMAP 1'); ax.set_ylabel('UMAP 2')
ax.legend()
plt.tight_layout()
plt.show()
print("INSIGHT: Red stars = flagged misplaced or anomalous X-rays.")

from sklearn.cluster import DBSCAN
print("✓ Fixed")

from sklearn.cluster import DBSCAN
import umap as umap_lib

print("Re-running UMAP...")
reducer     = umap_lib.UMAP(n_components=2, random_state=42,
                              n_neighbors=15, min_dist=0.1)
images_umap = reducer.fit_transform(images_pca)
print("✓ images_umap ready")

# Now run DBSCAN
dbscan    = DBSCAN(eps=0.5, min_samples=5)
db_labels = dbscan.fit_predict(images_umap)

n_clusters = len(set(db_labels)) - (1 if -1 in db_labels else 0)
n_noise    = (db_labels == -1).sum()
print(f"✓ DBSCAN done — Clusters: {n_clusters} | Noise: {n_noise}")

fig, ax = plt.subplots(figsize=(10,8))
unique_labels = sorted(set(db_labels))
cmap = plt.cm.tab10(np.linspace(0,1,max(len(unique_labels),2)))
for i, label in enumerate(unique_labels):
    mask = db_labels == label
    if label == -1:
        ax.scatter(images_umap[mask,0], images_umap[mask,1],
                   c='red', alpha=0.6, s=50, marker='x', label='Outliers')
    else:
        ax.scatter(images_umap[mask,0], images_umap[mask,1],
                   color=cmap[i], alpha=0.6, s=15,
                   label=f'Cluster {label}')
ax.set_title('DBSCAN Clustering on UMAP', fontsize=14, fontweight='bold')
ax.set_xlabel('UMAP 1'); ax.set_ylabel('UMAP 2')
ax.legend()
plt.tight_layout()
plt.show()

print("Detecting misplaced X-rays...")
misplaced_flags = []
for i in range(len(images)):
    risk = 0
    if anomaly_labels[i] == -1: risk += 2
    if db_labels[i] == -1:      risk += 1
    if anomaly_scores[i] < -0.1: risk += 1
    misplaced_flags.append(risk)

misplaced_flags = np.array(misplaced_flags)
high_risk = misplaced_flags >= 2

print(f"Total images:      {len(images)}")
print(f"High risk:         {high_risk.sum()} ({high_risk.sum()/len(images)*100:.1f}%)")
print(f"Low risk:          {(~high_risk).sum()}")

misplaced_indices = np.where(high_risk)[0][:6]
if len(misplaced_indices) > 0:
    fig, axes = plt.subplots(1, len(misplaced_indices), figsize=(15,4))
    if len(misplaced_indices) == 1: axes = [axes]
    for ax, idx in zip(axes, misplaced_indices):
        img = cv2.imread(image_paths[idx], cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (128,128))
        ax.imshow(img, cmap='gray')
        ax.set_title(f'FLAGGED\nRisk:{misplaced_flags[idx]}',
                     color='red', fontweight='bold', fontsize=9)
        ax.axis('off')
    fig.suptitle('Flagged Misplaced X-rays', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()
print("✓ Misplacement detection complete")

print("\n" + "="*55)
print("  X-RAY MISPLACEMENT DETECTION — COMPLETE")
print("="*55)
print(f"Dataset:          Chest X-Ray Pneumonia (Kaggle)")
print(f"Images loaded:    {len(images)}")
print(f"PCA components:   50")
print(f"K-Means clusters: {best_k} (Silhouette: {sil_score:.4f})")
print(f"DBSCAN clusters:  {n_clusters} (Noise: {n_noise})")
print(f"Anomalies found:  {n_anomalies} ({n_anomalies/len(images)*100:.1f}%)")
print(f"High risk images: {high_risk.sum()}")
print(f"\nWhat this proves to Canadian employers:")
print(f"  1. Computer Vision — image processing with OpenCV")
print(f"  2. Unsupervised ML — clustering without labels")
print(f"  3. Anomaly Detection — Isolation Forest")
print(f"  4. Dimensionality Reduction — PCA + UMAP")
print(f"  5. Medical AI — healthcare domain knowledge")
print("="*55)
print("NEXT: Download models → push to GitHub → deploy Streamlit")
print("="*55)

import os
files = os.listdir('/content')
print("Files in /content:")
for f in files:
    print(f" - {f}")

import pickle
import pandas as pd
import os

print("Saving all models...")

pickle.dump(kmeans,     open('/content/kmeans_model.pkl','wb'))
pickle.dump(iso_forest, open('/content/isolation_forest.pkl','wb'))
pickle.dump(pca,        open('/content/pca_model.pkl','wb'))
pickle.dump(scaler,     open('/content/scaler.pkl','wb'))

results_df = pd.DataFrame({
    'image_path':     image_paths,
    'true_label':     labels,
    'kmeans_cluster': km_labels,
    'anomaly_label':  anomaly_labels,
    'anomaly_score':  anomaly_scores,
    'risk_score':     misplaced_flags,
    'is_misplaced':   high_risk,
    'umap_x':         images_umap[:,0],
    'umap_y':         images_umap[:,1]
})
results_df.to_csv('/content/xray_results.csv', index=False)

print("✓ All files saved!")
print("Files in /content:")
for f in os.listdir('/content'):
    print(f"  - {f}")

from google.colab import drive
drive.mount('/content/drive')
import shutil, os

save_path = '/content/drive/MyDrive/xray_project/'
os.makedirs(save_path, exist_ok=True)

shutil.copy('/content/kmeans_model.pkl', save_path)
shutil.copy('/content/isolation_forest.pkl', save_path)
shutil.copy('/content/pca_model.pkl', save_path)
shutil.copy('/content/scaler.pkl', save_path)
shutil.copy('/content/xray_results.csv', save_path)

print("✓ All files saved to Google Drive!")